### ISSUE TITLE
bytes broken

### ISSUE THREAD

**Issue by Bernkastel-0** [meishuu/tera-data-parser-js#8]
When an event is logged with a protocol containing bytes and fed straight back to the client with dispatch.toClient, the output is not correct.

E.g. with S_SPAWN_USER def version 1-3, the bytes variables on detail will always produce deformed player characters when injected. Changing this to string temporarily fixes this problem, presumably because parser doesn't handle bytes correctly.

**Comment by meishuu** [comment]
Can you provide a code example? AFAIK the only test failures right now are with logging.

I believe the problem you're *actually* experiencing is that there's no guarantee `Buffer` data will remain correct after a hook has been called (I presume this is due to encryption). If you want to be sure they keep their values, you will need to make a copy. I suppose this sort of thing should be noted in the README or something.
